### PR TITLE
Improving navbar and small design issues

### LINKED ISSUE #35: Adjust Site Style to FOSSASIA, fix small design issues and adjust colors
* [ ] Fix the menu bar - currently it disappears when scrolling
* [ ] Re-use the FOSSASIA style top menu bar and include the science hack logo (in white) on the top left
* [ ] Take out "Register Here" on top bar
* [ ] Change top background to red style
* [ ] Change link color to red across page
* [ ] Separate css from pages

screenshot from 2017-01-03 22-03-15

### PR DESCRIPTION
**Pull request by alejoheredia**
@mariobehling @jig08 Fixes #35 
Preview: https://heredroky.github.io/sciencehack.in/index.html

I hope you like, please when you review it, give me feedback 😄 ,

Cheers!

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
Looks improvised. 
@mariobehling Your views pls before we merge this :)

**Comment by mariobehling** [comment]
@Heredroky Please check all pages. Mentors page is not changed and links from mentors page are not working. Thank you.

**Comment by alejoheredia** [comment]
@mariobehling What about now?

**Comment by jigyasa-grover** [comment]
@Heredroky Nice. Pls squash all your commits into one and rename it as `Fixes #<issue number> : <commit message>`. Thanks !

**Comment by alejoheredia** [comment]
@jig08 @mariobehling Check it out, I have just squashed that 😄

**Comment by mariobehling** [comment]
Good job. 

Please check some inconsistencies still:

screenshot from 2017-01-05 13-48-47

The scroll over effect on the projects does not work anymore. Maybe change scroll over background from blue to grey here as well. Cheers.

**Comment by alejoheredia** [comment]
@mariobehling Please check it out, I fixed it

**Comment by mariobehling** [comment]
Nice. Merging it. Thank you!

**Comment by alejoheredia** [comment]
😄

**Pull request merged**
